spring:
  application:
    name: "Chatting-Service"
  cloud:
    config:
      enabled: false
      discovery:
        locator: true
  datasource:
    url: "jdbc:postgresql://pg-279e6e20-tarektempo015-db92.i.aivencloud.com:28688/defaultdb?ssl=true&sslmode=require"
    username: "avnadmin"
    password: "AVNS_RvLdahdOHCXA00EfjMN"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: "update"
      show-sql: "true"



server:
  port: 8091

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    gateway:
      enabled: true
      lowerCaseServiceId: true

info:
  app:
    name: "Chat-service"
    description: "Chat-service"