spring:
  application:
    name: "Gateway-service"
  cloud:
    config:
      enabled: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      discovery:
        locator: true
      routes:
        - id: "patient-service"
          uri: lb://Patient-Service
          predicates:
            - Path=/api/patient/**
        - id: "doctor-service"
          uri: lb://Doctor-Service
          predicates:
            - Path=/api/doctor/**
        - id: "user-authentication-service"
          uri: lb://Auth-Service
          predicates:
            - Path=/auth/**
        - id: "ai-chatbot-service"
          uri: lb://Ai-Chatbot-Service
          predicates:
            - Path=/chatbot/**
        - id: "chatting-service-http"
          uri: lb://Chatting-Service
          predicates:
            - Path=/chat/**
        - id: chatting-service-ws
          uri: lb://Chatting-Service
          predicates:
            - Path=/ws/**
        - id: "article-service"
          uri: lb://Article-Service
          predicates:
            - Path=/article/**
        - id: "appointment-service"
          uri: lb://Appointment-Service
          predicates:
            - Path=/api/appointment/**
        - id: "notification-service"
          uri: lb://Notification-Service
          predicates:
            - Path=/notification/**

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    gateway:
      enabled: true
      lowerCaseServiceId: true

info:
  app:
    name: "Gateway-service"
    description: "Gateway-service"

jwt:
  secret-key: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"