spring:
  application:
    name: "Gateway-service"
  cloud:
    config:
      enabled: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      discovery:
        locator: true
      routes:
        - id: "patient-service"
          uri: lb://Patient-Service
          predicates:
            - Path=/api/patient/**
          filters:
            - name: CircuitBreaker
              args:
                name: patient-service
        - id: "doctor-service"
          uri: lb://Doctor-Service
          predicates:
            - Path=/doctor/**
          filters:
            - name: CircuitBreaker
              args:
                name: doctor-service
        - id: "user-authentication-service"
          uri: lb://Auth-Service
          predicates:
            - Path=/auth/**
        - id: "ai-chatbot-service"
          uri: lb://Ai-Chatbot-Service
          predicates:
            - Path=/chatbot/**
          filters:
            - name: CircuitBreaker
              args:
                name: ai-chatbot-service
        - id: "chatting-service"
          uri: lb://Chatting-Service
          predicates:
            - Path=/Chatting/**
          filters:
            - name: CircuitBreaker
              args:
                name: chatting-service
        - id: "article-and-forum-service"
          uri: lb://Article-Service
          predicates:
            - Path=/article/**
          filters:
            - name: CircuitBreaker
              args:
                name: article-and-forum-service
        - id: "appointment-service"
          uri: lb://Appointment-Service
          predicates:
            - Path=/appointment/**
          filters:
            - name: CircuitBreaker
              args:
                name: appointment-service

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    gateway:
      enabled: true
      lowerCaseServiceId: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 4
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

info:
  app:
    name: "Gateway-service"
    description: "Gateway-service"

jwt:
  secret-key: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"