spring:
  application:
    name: "VerificationService"
  cloud:
    config:
      enabled: false

server:
  port: 8084

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

endpoints:
  shutdown:
    enabled: true


persona:
  secret-key: persona_sandbox_0d767e24-8333-43a3-b73c-15a8e21f7ae0

inquiry:
  template-id: itmpl_HHfacNC4rg2pKAFVmzkgUGbmStoH